# Generated by Django 2.2.3 on 2019-07-14 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='up_votes',
        ),
        migrations.AlterField(
            model_name='rating',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_rating_fk', to='questions.Question'),
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('up_vote', models.BooleanField(default=False)),
                ('down_vote', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_vote_fk', to='questions.Question')),
            ],
        ),
    ]
