# Generated by Django 2.2.3 on 2019-07-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_answer_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
